### PR TITLE
8.0 4223 statement match journal channel

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Review by NL66278 — CHANGES_REQUESTED** [review]
This is using hard coded Journal names. I think I have already many times warned against these kind of solutions, that disintegrate the moment a name changes, a journal is added etc.

If a user talks about this journal goes with that sale channel, we should not hardcode this stuff, but provide a way to link a journal to a sales channel. (So sales_channel_id Many2one field on journal).

Then we know that sales channels should really be refactored into their own table/model. No time to that now, but you can already prepare by using the variable name sale_channel_model.

Where is the get_proper_channel method called?

**Comment by daramousk** [comment]
@NL66278 `get_proper_channel` is used in the rules like this '@get_proper_channel@` When this is deployed I have to modify some rules on production by adding and extra clause that contains this call

**Comment by daramousk** [comment]
@NL66278 Check my latest changes, I have created two migration functions that take care of everything

**Comment by NL66278** [comment]
@daramousk Looks great. From a philosophical point of view the migration of the pure Ari stuff might go into an Ari module, but I guess this is used by Ari only anyway.

Did you test the migration and the working of the rules after migration? In that case I could merge

**Comment by daramousk** [comment]
@NL66278 I seems that in order for this to execute I have to remove set `noupdate="0"` once and then revert it after the migration happens because it does not run when it is 1. Other than that the rules seem to run ok. Still I will ask for client to test again

**Comment by NL66278** [comment]
@daramousk I was already a bit afraid of the noupdate flag.

You might leave out the noupdate flag altogether, but where you search for journals to update include the criterium that sales_channel must not already have been set. (To prevent phony updates).

**Comment by daramousk** [comment]
@NL66278 Well the no update flag should have worked properly. In any case I have removed it and added the extra case in the domain.

**Comment by NL66278** [comment]
OK, now just waiting for positive test results.

**Review by NL66278 — APPROVED** [review]

**Comment by daramousk** [comment]
@NL66278 Client tested and approved. See the relevant ticket.

**Pull request merged**
